name: "xxh-prng-CI"

on:
  push:
    branches: ['**']
  pull_request:
  release:
    types: [published]

env:
  NON_INTERACTIVE: 1

jobs:
  linux:
    name: Linux build
    runs-on: ubuntu-latest
    steps:
      - uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: crossbuild-essential-amd64 crossbuild-essential-i386 crossbuild-essential-arm64
          version: 1.0
      - uses: actions/checkout@v4
      - run: mkdir dist
      - run: |
          ./deploy.sh x86_64-linux-gnu-gcc x86_64-linux-gnu-strip
          mv -vf bin/xxh_rand dist/xxh_rand-x86_64
      - run: |
          ./deploy.sh i686-linux-gnu-gcc i686-linux-gnu-strip
          mv -vf bin/xxh_rand dist/xxh_rand-i686
      - run: |
          ./deploy.sh aarch64-linux-gnu-gcc aarch64-linux-gnu-strip
          mv -vf bin/xxh_rand dist/xxh_rand-aarch64
      - uses: actions/upload-artifact@v4
        with:
          name: xxh64-prng-linux
          path: dist/

  windows:
    name: Windows build
    runs-on: windows-latest
    steps:
      - uses: microsoft/setup-msbuild@v2
      - uses: actions/checkout@v4
      - run: New-Item -ItemType Directory dist
      - run: cmd.exe /c deploy.cmd
      - run: |
          Move-Item -Force -Path bin/Win32/Release/xxh_rand-x86.exe -Destination dist/
          Move-Item -Force -Path bin/x64/Release/xxh_rand-x64.exe -Destination dist/
          Move-Item -Force -Path bin/ARM64/Release/xxh_rand-a64.exe -Destination dist/
      - uses: actions/upload-artifact@v4
        with:
          name: xxh64-prng-windows
          path: dist/
